name: CI Staging (NEW)

on:
  workflow_dispatch:
  push:
    branches:
      - main_candidate
    paths-ignore:
      - ".github/**"

permissions: {}

jobs:
  # test:
  #   ...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Staging deploy
        uses: lidofinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "lidofinance/infra-mainnet"
          TARGET_WORKFLOW: "deploy_staging_mainnet_ethereum_validators_monitoring.yaml"
          TARGET: "main"
