name: Create tag and trigger deploy
on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Create tag and release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag value
        id: tag
        run: |
          TAG="$(grep -oP '\d+\.\d+\.\d+' <<< "$MESSAGE")"
          echo "$TAG"
          echo "::set-output name=tag::${TAG}"
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
      - name: Create and push tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin --tags
      - name: Create release
        uses: lidofinance/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}

  deploy-trigger:
    needs: bump
    name: Trigger build and PR creation in the infra-mainnet
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/ci-prod.yml
    secrets: inherit
    with:
      tag: ${{ needs.bump.outputs.tag}}
