name: Create tag and trigger deploy
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  bump:
    name: Create tag and release
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Get tag value
        id: tag
        run: |
          TAG="$(grep -oP '^chore\(release\).*\K(\d+\.\d+\.\d+)' <<< "$MESSAGE")"
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
      - name: Create and push tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push https://x-access-token:${{ github.token }}@github.com/$GITHUB_REPOSITORY --tags
      - name: Create release
        uses: lidofinance/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
      # Publish container image to github packages
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.tag.outputs.tag }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-trigger:
    needs: bump
    name: Trigger build and PR creation in the infra-mainnet
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    uses: ./.github/workflows/ci-prod.yml
    secrets: inherit
    with:
      tag: ${{ needs.bump.outputs.tag }}
